import { Prisma } from "@prisma/client";

export const randomSelect = Prisma.sql`
  "Film"."id",
  "Film"."slug",
  "Film"."title",
  "Film"."originalTitle",
  "Film"."year" AS "releaseYear",
  "Film"."year",
  "Film"."runtime",
  "Film"."genres",
  "Film"."contentType",
  "Film"."plot",
  "Film"."director",
  "Film"."posterUrl",
  "Film"."posterColor",
  "Film"."backdropUrl",
  "Film"."imdbRating",
  "Film"."rtScore",
  "Film"."imdbTopMovieRank",
  "Film"."imdbTopTvRank",
  "Film"."oscarCategories",
  "Film"."oscarNominations",
  "Film"."oscarWins",
  "Film"."ggCategories",
  "Film"."ggNominations",
  "Film"."ggWins",
  "Film"."cannesCategories",
  "Film"."cannesNominations",
  "Film"."cannesWins",
  "Film"."berlinCategories",
  "Film"."berlinNominations",
  "Film"."berlinWins"
`;
