import { Prisma } from "@prisma/client";

export const filmListSelect = Prisma.sql`
  "Film"."id",
  "Film"."slug",
  "Film"."title",
  "Film"."originalTitle",
  "Film"."year" AS "releaseYear",
  "Film"."year",
  "Film"."genres",
  "Film"."contentType",
  "Film"."posterUrl",
  "Film"."posterColor",
  "Film"."imdbRating",
  "Film"."rtScore",
  "Film"."imdbTopMovieRank",
  "Film"."imdbTopTvRank",
  "Film"."certificate",
  "Film"."tvType",
  "Film"."tvStartYear",
  "Film"."tvEndYear",
  "Film"."tvSeasons",
  "Film"."tvEpisodes",
  "Film"."oscarNominations",
  "Film"."oscarWins",
  "Film"."ggNominations",
  "Film"."ggWins",
  "Film"."cannesNominations",
  "Film"."cannesWins",
  "Film"."berlinNominations",
  "Film"."berlinWins"
`;

export const filmDetailSelect = {
  id: true,
  slug: true,
  tmdbId: true,
  imdbId: true,
  title: true,
  originalTitle: true,
  releaseYear: true,
  runtime: true,
  genres: true,
  contentType: true,
  plot: true,
  director: true,
  cast: true,
  language: true,
  posterUrl: true,
  posterColor: true,
  backdropUrl: true,
  trailerUrl: true,
  imdbRating: true,
  rtScore: true,
  imdbTopMovieRank: true,
  imdbTopTvRank: true,
  certificate: true,
  tvType: true,
  tvStartYear: true,
  tvEndYear: true,
  tvSeasons: true,
  tvEpisodes: true,
  oscarNominations: true,
  oscarWins: true,
  oscarCategories: true,
  ggNominations: true,
  ggWins: true,
  ggCategories: true,
  cannesNominations: true,
  cannesWins: true,
  cannesCategories: true,
  berlinNominations: true,
  berlinWins: true,
  berlinCategories: true,
  watchProviders: true,
  isPickOfDay: true,
  pickOfDayDate: true,
} satisfies Prisma.FilmSelect;
