export const ROLL_BATTLE_TOTAL_ROUNDS = 5;
export const ROLL_BATTLE_SET_SIZE = ROLL_BATTLE_TOTAL_ROUNDS + 1;
export const ROLL_BATTLE_CANDIDATE_POOL_SIZE = 18;
export const ROLL_BATTLE_SELECTION_DELAY_MS = 900;
export const ROLL_BATTLE_COPY_STATUS_MS = 2000;
