"use client";

import type { FilterState } from "@cineroll/types";

export const DEFAULT_FILTERS: FilterState = {
  search: "",
  person: "",
  director: "",
  femaleDirectorOnly: false,
  awardBodies: [],
  winnerOnly: false,
  nominatedOnly: false,
  categories: [],
  awardYear: null,
  awardYearMin: null,
  awardYearMax: null,
  languages: [],
  genres: [],
  genresMatchAll: false,
  countries: [],
  contentTypes: [],
  runtimeMin: null,
  runtimeMax: null,
  yearMin: null,
  yearMax: null,
  nominationCount: null,
  ceremonyCount: null,
  imdbRatingMin: 0,
  imdbRatingMax: null,
  rtScoreMin: 0,
  certificate: "",
  imdbTopMoviesOnly: false,
  imdbTopTvOnly: false,
  imdbTopExclude: false,
  winsMin: null,
  winsMax: null,
  tvType: "",
  excludeWatched: false,
  sort: "wins",
  sortOrder: "desc",
  page: 1,
};
