export const GENRE_ALIASES: Record<string, string> = {
  "period piece": "History",
  "rom com": "Romance",
  "sci fi": "Science Fiction",
  animated: "Animation",
  anime: "Animation",
  biopic: "Biography",
  doc: "Documentary",
  documentaries: "Documentary",
  historical: "History",
  period: "History",
  romcom: "Romance",
  scifi: "Science Fiction",
  "science fiction": "Science Fiction",
  space: "Science Fiction",
};

export const CATEGORY_ALIASES: Record<string, string> = {
  "best actor": "Actor",
  "best actress": "Actress",
  "best director": "Directing",
  "best foreign language": "International Feature",
  "best picture": "Best Picture",
  "best screenplay": "Writing",
  "best writing": "Writing",
  cinematographer: "Cinematography",
  "foreign language": "International Feature",
};

export const LANGUAGE_NAME_TO_CODE: Record<string, string> = {
  american: "en",
  brazil: "pt",
  brazilian: "pt",
  british: "en",
  cantonese: "zh",
  china: "zh",
  chinese: "zh",
  deutsch: "de",
  english: "en",
  france: "fr",
  french: "fr",
  german: "de",
  germany: "de",
  italian: "it",
  italy: "it",
  japan: "ja",
  japanese: "ja",
  korea: "ko",
  korean: "ko",
  mandarin: "zh",
  mexican: "es",
  mexico: "es",
  portugal: "pt",
  portuguese: "pt",
  russia: "ru",
  russian: "ru",
  spain: "es",
  spanish: "es",
  sweden: "sv",
  swedish: "sv",
  uk: "en",
  usa: "en",
};
